//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeqTank.Services.MakoRunners.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"ew0KICAiQ29tcGFueUlkIjogMTEsDQogICJDb21wYW55TmFtZSI6ICJSU29sdXRpb24iLA0KICAiQ29tcGFueUtleSI6ICJSU29sIiwNCiAgIlVzZXJuYW1lIjogIlJTb2x1dGlvbl9NYWtvUnVubmVyX0E0ODQyODc0LUI1RUQtNEFFNS1BN0M0LTBFNDgiLA0KICAiUHdkIjogImJ6cGJlM2xCSnpYR2IrOVQyZTlkc2UzOUtMOVdNSGowYUN4TmZualp6SGk3ZzdFdEI4TzlYQT09IiwNCiAgIkNyeXB0S2V5IjogInk3eXl2cGJzYkFMOTdmR0FRanB5VTEzbWx4THVMU1ZGNFZHbDVSRVVKVWM9IiwNCiAgIkF1dGhLZXkiOiAiWEFVbExUY2ZDaTVSNU9uelhxaHpTQjBJdEFVQ3NCeSt4T1h2cHBEWlBFND0iDQp9")]
        public string CompanyId11 {
            get {
                return ((string)(this["CompanyId11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunServerJobsInParallel {
            get {
                return ((bool)(this["RunServerJobsInParallel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RunAzureJobaInParallel {
            get {
                return ((bool)(this["RunAzureJobaInParallel"]));
            }
        }
    }
}
